server:
  port: 9092
#Eureka
eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    register-with-eureka: true
    fetch-registry: false
    eureka-server-connect-timeout-seconds: 3000
spring:
  datasource:
    schema: classpath:/db/migration/schema
    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/xxojugcd?createDatabaseIfNotExist=true&useSSL=true
    driver-class-name: org.postgresql.Driver
    username: xxojugcd
    password: qOub7zE3Ow5zPupe1zSaBtZooHzY_avl
  #JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: false
    enabled: true
    locations: classpath:/db/migration