#informações da api
openapi: 3.0.1
info:
  description: "👥 Microservice client management system made with SpringBoot. 💳 Phoebus @paystore
    training project in partnership with @ayty-org"
  version: "1.0.0"
  title: "Book-Store: livraria"
  contact:
    email: "josinaldo.pontes@phoebustecnologia.com.br"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: "client-controller"
    description: "All about client in book store"
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: https://localhost:8080
  - url: http://localhost:8080/v3/docs

paths:
  /v1/api/client/{id}:
    get:
      tags:
        - client-controller
      operationId: find_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
    put:
      tags:
        - client-controller
      operationId: update_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'
        required: true
      responses:
        "204":
          description: No Content
    delete:
      tags:
        - client-controller
      operationId: delete_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: No Content
  /v1/api/client:
    get:
      tags:
        - client-controller
      operationId: findAll_1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientDTO'
    post:
      tags:
        - client-controller
      operationId: insert_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'
        required: true
      responses:
        "201":
          description: Created
  /v1/api/client/:
    get:
      tags:
        - client-controller
      operationId: findPage_1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageClientDTO'
components:
  schemas:
    ClientDTO:
      required:
        - age
        - email
        - name
        - phone
        - sexo
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          minimum: 2
          type: integer
          format: int32
        phone:
          type: string
        email:
          type: string
        sexo:
          type: string
          enum:
            - MASCULINO
            - FEMININO
            - OUTRO
    PageClientDTO:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        pageable:
          $ref: '#/components/schemas/Pageable'
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/ClientDTO'
        empty:
          type: boolean
    Pageable:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        paged:
          type: boolean
        unpaged:
          type: boolean
        offset:
          type: integer
          format: int64
    Sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean